version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - expensetracker-network

  springboot-container:
    image: springbootmysql
    container_name: springboot-container
    depends_on:
      - mysqldb
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - expensetracker-network
    command: ["./wait-for-it.sh", "mysqldb:3306", "java", "-jar", "/expensetracker.jar"]

networks:
  expensetracker-network:
    driver: bridge
