spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expensetracker
    username: root
    password: Anshu@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api/v1

jwt:
  secret: "your-very-long-secret-key-that-is-at-least-64-characters-long-your-very-long-secret-key-that-is-at-least-64-characters-long"
