spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expensetracker
    username: root
    password: Anshu@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api/v1